--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: currencyconvert
    version: v1
  name: currencyconvert
spec: 
  strategy: # Default, so usually not specified
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1  # specifies the maximum number of Pods that can be created over the desired number of Pods
      maxUnavailable: 25% #specifies the maximum number of Pods that can be unavailable during the update process
  replicas: 1
  selector: 
    matchLabels: 
      app: currencyconvert
      version: v1
  template: 
    metadata: 
      labels: 
        app: currencyconvert
        version: v1

    spec: 

      containers: 
        - 
          image: "amrutakhadilkar/currencyconvert"
          imagePullPolicy: Always
          name: currencyconvert
          ports: 
#          - containerPort: 8091   
          - name: httpport
            containerPort: 8091
            hostPort: 8091      
 