apiVersion: v1
kind: Service
metadata:
  name: currencyconvert
  labels: 
    app: currencyconvert
    version: v1
  
spec:
  selector:
    app: currencyconvert
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091