--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: managecurrency
    version: v1
  name: managecurrency
spec: 
  strategy: # Default, so usually not specified
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1  # specifies the maximum number of Pods that can be created over the desired number of Pods
      maxUnavailable: 25% #specifies the maximum number of Pods that can be unavailable during the update process
  replicas: 1
  selector: 
    matchLabels: 
      app: managecurrency
      version: v1
  template: 
    metadata: 
      labels: 
        app: managecurrency
        version: v1

    spec: 

      containers: 
        - 
          image: "amrutakhadilkar/managecurrency"
          imagePullPolicy: Always
          name: managecurrency
          ports: 
#          - containerPort: 8092   
          - name: httpport
            containerPort: 8092
            hostPort: 8092      
  