--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: managecurrency
    version: v1
  name: managecurrency
spec: 
  ports: 
    - 
      name: http
      port: 8092
      targetPort: 8092

  selector: 
    app: managecurrency
    version: v1
  type: NodePort